spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  cache:
    type: simple # Use simple cache in development instead of Redis

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    dev.dexellent.dexapi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.cache: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8080

# H2 Console (optional for development)
# spring:
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
