spring:
  datasource:
    url: ${DATABASE_URL}

  data:
    redis:
      url: ${REDIS_URL}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.dexellent.dexapi: INFO
