spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dexapi
    username: dexapi
    password: dexapi_dev

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    com.dexellent.dexapi: DEBUG
